mode: "block-on-error" # or "comment-only"

comment:
  updateInsteadOfSpam: true
  header: "ðŸ›¡ï¸ Denarixx Sentinel Report"

pr:
  titlePrefixes: ["feat:", "fix:", "chore:", "docs:", "refactor:", "test:"]
  minBodyChars: 120
  requiredSections: ["What", "Why", "How tested"]
  taskRegex: "(#\\d+|JIRA-\\d+|TASK-\\d+)"

size:
  warnFilesChangedOver: 25
  warnLinesChangedOver: 400

tests:
  warnIfCodeChangedWithoutTests: true
  codeGlobs: ["**/*.ts", "**/*.js", "**/*.py"]
  testGlobs: ["**/*test*.*", "**/*spec*.*", "**/tests/**", "**/test/**"]

rules:
  - name: "No app -> infra imports (generic)"
    severity: "warn"
    fileGlobs: ["**/*.ts", "**/*.js", "**/*.py"]
    forbidRegex:
      - "from\\s+.*infra"
      - "import\\s+.*infra"
      - "src/infra"

risk:
  enabled: true
  # blockIfScoreAbove: 90  # optional: block merge above this score
  sensitivePaths:
    - "**/auth/**"
    - "**/payments/**"
    - "**/billing/**"
    - "**/security/**"
    - "**/infra/**"
    - "**/migrations/**"
    - "**/.github/workflows/**"
    - "**/Dockerfile"
    - "**/docker/**"
    - "**/*config*.*"
    - "**/*.env*"
  dependencyFiles:
    - "**/package.json"
    - "**/package-lock.json"
    - "**/yarn.lock"
    - "**/pnpm-lock.yaml"
    - "**/requirements.txt"
    - "**/pyproject.toml"
    - "**/poetry.lock"
