mode: "block-on-error"

comment:
  updateInsteadOfSpam: true
  header: "🛡️ Denarixx Sentinel Report"

pr:
  titlePrefixes: ["feat:", "fix:", "chore:", "docs:", "refactor:", "test:"]
  minBodyChars: 120
  requiredSections: ["What", "Why", "How tested"]
  taskRegex: "(#\\d+|JIRA-\\d+|TASK-\\d+)"

size:
  warnFilesChangedOver: 25
  warnLinesChangedOver: 400

tests:
  warnIfCodeChangedWithoutTests: true
  codeGlobs: ["**/*.ts", "**/*.js", "**/*.py"]
  testGlobs: ["**/*test*.*", "**/*spec*.*", "**/tests/**", "**/test/**"]

risk:
  enabled: true
  sensitivePaths:
    - "**/auth/**"
    - "**/payments/**"
    - "**/billing/**"
    - "**/security/**"
    - "**/infra/**"
    - "**/migrations/**"
    - "**/.github/workflows/**"
    - "**/Dockerfile"
    - "**/docker/**"
    - "**/*config*.*"
    - "**/*.env*"
  dependencyFiles:
    - "**/package.json"
    - "**/package-lock.json"
    - "**/yarn.lock"
    - "**/pnpm-lock.yaml"
    - "**/requirements.txt"
    - "**/pyproject.toml"
    - "**/poetry.lock"

jsonOutput:
  enabled: true
  path: denarixx-sentinel-report.json

sarif:
  enabled: true
  path: denarixx-sentinel.sarif