name: "Denarixx Sentinel"
description: "PR Copilot Guard: PR quality checks, test heuristics, configurable rules (JS/Python-friendly)"
author: "Denarixx"
inputs:
  config:
    description: "Path to config YAML file"
    required: false
    default: ".denarixx-sentinel.yml"
  github-token:
    description: "GitHub token for commenting on PRs (usually secrets.GITHUB_TOKEN)"
    required: false
    default: "${{ github.token }}"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "shield"
  color: "purple"
